name: schedule-py-script-weekly

on:
  schedule:
    - cron: '0 0 * * 0' # At 00:00 on Sunday

jobs:
  run-py-script:
    runs-on: ubuntu-latest
    steps:
          
      - name: Check out repository
        uses: actions/checkout@v3 # checkout the repository content to github runner
        
      - name: Create json file
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "credentials.json"
          json: ${{ secrets.SECRET_JSON }}
          
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
                    
      - name: Execute py script
        run: python 1_collecting_data.py
